### ISSUE TITLE
Preview crashes on FlashDevelop 5.1.x

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/HaxeUILayoutPreview#8]
The following stacktrace is displayed:

System.Xml.XmlException: 'config' is an undeclared namespace. Line 104, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg, Int32 lineNo, Int32 linePos)
   at System.Xml.XmlTextReaderImpl.LookupNamespace(NodeData node)
   at System.Xml.XmlTextReaderImpl.ElementNamespaceLookup()
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at HaxeUILayoutPreview.OpenFLApplicationDescriptor.Load()
   at HaxeUILayoutPreview.TabDetails.CreatePreviewPlayer()
   at HaxeUILayoutPreview.TabDetails.GetPreviewPlayer(Int32 paneIndex)
   at HaxeUILayoutPreview.TabDetails.strip_SelectedTabChanged(Object sender, SelectedTabChangedEventArgs e)
   at Messir.Windows.Forms.TabStrip.OnTabSelected(TabStripButton tab)
   at Messir.Windows.Forms.TabStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by sebthom** [comment]
It was caused by `<config:hxtelemetry host="localhost" allocations="false" unless="android" />` in the project.xml
As a fix I am now declaring a dummy namespace in the project header tag, like `<project     xmlns:config="foobar" >`
